version: "3.8"

services:
  server-demo:
    image: demo-server-2
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "z10mz10m"
      MYSQL_DATABASE: "testing_todos"
    ports:
      - "3306:3306" # Adjust the port mapping as needed
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
